- name: Updating resolv.conf
  copy: 
    src: resolv.conf
    dest: /etc/resolv.conf

- name: Apt Update
  apt:
    update_cache: yes

- name: KVM libraries
  apt:
    name: 
      - qemu-kvm 
      - libvirt-daemon-system 
      - libvirt-clients
      - bridge-utils
      - virt-manager 
      - libvirt-bin 
      - ubuntu-vm-builder
      - virtinst
      - libosinfo-bin



