- name: Update apt-get repo and cache
  apt:
    update_cache: yes
- name: KVM libraries
  apt:
    name: 
      - qemu-kvm 
      - libvirt-daemon-system 
      - libvirt-clients
      -  bridge-utils

